trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo K8S Terraform Azure!
      displayName: 'Run a one-line script'
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'in28min-docker-hub'
    repository: 'kazem118/currency-exchange-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa2.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection2'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg2'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctkazemxyz'
    backendAzureRmContainerName: 'storageacctkazemcontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
